using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class BrickStorePlayerModel
{
    [RealtimeProperty(1, true, false)] private int _brickId;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class BrickStorePlayerModel : RealtimeModel {
    public int brickId {
        get {
            return _brickIdProperty.value;
        }
        set {
            if (_brickIdProperty.value == value) return;
            _brickIdProperty.value = value;
            InvalidateReliableLength();
        }
    }
    
    public enum PropertyID : uint {
        BrickId = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _brickIdProperty;
    
    #endregion
    
    public BrickStorePlayerModel() : base(null) {
        _brickIdProperty = new ReliableProperty<int>(1, _brickId);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _brickIdProperty.UnsubscribeCallback();
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _brickIdProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _brickIdProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.BrickId: {
                    changed = _brickIdProperty.Read(stream, context);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _brickId = brickId;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
